name: Graudit ASP SAST Scan on PR

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  graudit_scan:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SAST_SECURITY_SLACK_WEBHOOK}}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      ASP_PR_URL: ${{ github.event.pull_request.html_url }}
      ASP_PR_CREATOR: ${{ github.event.pull_request.user.login }}
      ASP_HEAD_COMMIT: ${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}
      ASP_WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      ASP_SENDER: ${{ github.event.sender.login }}

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: head
        persist-credentials: false

    - name: Checkout base branch code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: base
        persist-credentials: false

    - name: Setup Graudit CLI
      run: |
        set -e
        git clone https://github.com/wireghoul/graudit.git "${{ github.workspace }}/graudit"
        cd graudit
        git checkout 132db329a68ee64b147d1b6c91d26e242940a2ec
        echo "${{ github.workspace }}/graudit" >> $GITHUB_PATH
      shell: bash

    - name: Run Graudit scan on PR code
      run: |
        set -e
        cd "${{ github.workspace }}/head"
        graudit -B -d "${{ github.workspace }}/graudit/signatures/asp.db" -x "*/Backup/*,*.bak,*Copy*,*.exe" . 2>&1 | tee "${{ github.workspace }}/head.log"
        
        cd "${{ github.workspace }}/base"
        graudit -B -d "${{ github.workspace }}/graudit/signatures/asp.db" -x "*/Backup/*,*.bak,*Copy*,*.exe" . 2>&1 | tee "${{ github.workspace }}/base.log"
      shell: bash
      if: ${{ success() }} 

    - name: Compare scan results
      run: |
        set -e
        diff -u "${{ github.workspace }}/base.log" "${{ github.workspace }}/head.log" > "${{ github.workspace }}/new_issues.log" || true
        if [ -s "${{ github.workspace }}/new_issues.log" ]; then
          echo "New issues found in the PR code:"
          cat "${{ github.workspace }}/new_issues.log"
          exit 1
        else
          echo "No new issues introduced by the PR"
        fi
      shell: bash

    - name: Send Slack Notification
      if: failure()
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":red-alert: *ASP SAST Scan Failed*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "`Workflow Run:` ${{ env.ASP_WORKFLOW_RUN_URL }}\n\n`Pull Request:` ${{ env.ASP_PR_URL }}\n\n`Head Commit:` ${{ env.ASP_HEAD_COMMIT }}\n\n`PR Creator:` *${{ env.ASP_PR_CREATOR }}*\n\n`Latest Committer:` *${{ env.ASP_SENDER }}*\n\n"
                }
              }
            ]
          }
