name: Bandit Python Sast Scanner
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  bandit-analyze:
    runs-on: ubuntu-latest
    name: Bandit Analysis
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #v5.5.0
        with:
          python-version: 3.9

      - name: Install Bandit
        shell: bash
        run: pip install bandit===1.8.3

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Run Bandit
        shell: bash
        run: |
          if [ -s bandit.json ]; then
            bandit -x .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg -r . -f json -b bandit.json -o bandit-output.json
            jq -Sr 'if .results[] | ">> Issue: [\(.test_id):\(.test_name)] \(.issue_text)\n   Severity: \(.issue_severity | ascii_upcase)   Confidence: \(.issue_confidence | ascii_upcase)\n   CWE: CWE-\(.issue_cwe.id) (\(.issue_cwe.link))\n   More Info: \(.more_info)\n   Location: \(.filename):\(.line_number):\(.col_offset)\nCode:\n\(.code)"' bandit-output.json
          else
            bandit -x .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg -r .
          fi
