name: Bandit Python Sast Scanner
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  bandit-analyze:
    runs-on: ubuntu-latest
    name: Bandit Analysis
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #v5.5.0
        with:
          python-version: 3.9

      - name: Install Bandit
        shell: bash
        run: pip install bandit===1.8.3

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Run Bandit
        shell: bash
        run: |
         bandit -x .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg -r .
      
